version: '3'
services:
  app:
    build: .
    container_name: studyService
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./study:/app
    restart: always
