name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push 될 때 배포 시작

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_KEY }}  # GitHub Secrets에서 AWS_KEY를 가져옴

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/OnlineAIMakers/study
            docker pull study-app:latest  # Docker 이미지 업데이트
            docker-compose -f /home/ec2-user/OnlineAIMakers/study/docker-compose.yml up -d  # Docker Compose로 서비스 실행
          EOF
